/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:d20988ce-a704-48d0-8d37-e34ab156b3d9",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_D8yzXxr6g",
    "aws_user_pools_web_client_id": "4q40ot3t81cqghejaaqlungult",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://v72gbxliuvdnlpz4q75cgkltte.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-5rwrkgeepvfw7elovybp22qpsm"
};


export default awsmobile;
